version: '3.8'
services:
  traefik:
    image: traefik:v3.0
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
    ports:
      - "8080:80"
      - "8081:8080" # Traefik dashboard
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro

  client:
    build:
      context: ./client-react
    depends_on:
      - server

  server:
    build:
      context: ./server
    volumes:
      - server_data:/app/data
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  server_data:
